language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.6
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.6
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - cd ../bin